/**
    Classe dérivée de jDialog pour acheter une carte loto
**/
import javax.swing.*;
/**
 *
 * @author thomasnicolle
 */
public class AchatCarteDlg extends javax.swing.JDialog {

    // attributs
    private LesJoueurs ljc; // permet de stocker la liste des joueurs et leurs informations
    private int nbCol, nbLig, nbNum; // connaitre les dimension choisis par l'utilisateur
    private Joueur jc; // attribuer la carte au joueur sélectionné
    private CarteLoto cc; // stocker la carte généré par le programme
    private boolean achat; // savoir si l'utilisateur achète ou non la carte loto
    
    // Getters
    public CarteLoto getCarte() {
        return cc;
    }
    
    public boolean getAchat() {
        return this.achat;
    }
    
    // Méthodes
    public void remplirListeJoueurs() {
        for (int i = 0; i < ljc.getNbJoueur(); i++) {
            ListeJoueurs.addItem(ljc.getJoueur(i).getPseudo());
        }
    }

    public void initCarte() {
        Panneau.removeAll();
        cc = new CarteLoto(nbCol, nbNum); // Initialisation de la CarteLoto avec le nombre de colonnes et de numéros voulu
        // carte loto instancie ici pour regenrer une carte apres achat ou demande du joueur
        Panneau.setLayout(new java.awt.GridLayout(nbLig, nbCol));
        for (int i = 0; i < this.nbLig; i++) {
            for (int j = 0; j < this.nbCol; j++) {
                JButton bt=new JButton();
                Panneau.add(bt);
            }
        }
    }
    
    public void afficheCarte() {
        for(int i=0; i<this.nbLig; i++) {
            for(int j=0; j<this.nbCol; j++) {
                JButton bt = (JButton)(Panneau.getComponent(i*nbCol+j));
                int val = cc.getCase(i,j) ;
                if(val==0) {
                    bt.setText("");
                } else {
                    bt.setText(""+val);
                }
            }
        }
    }

    // Constructeurs
    private AchatCarteDlg(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public AchatCarteDlg(java.awt.Frame parent, boolean modal, LesJoueurs list, int nl, int nc, int nn) {
        super(parent, modal);
        initComponents();
        ljc = list; // récupération des valeurs options et liste des joueurs
        nbCol = nc;
        nbLig = nl;
        nbNum = nn;
        achat = false; // achat pas encore effectué
        jc = new Joueur(ljc.getJoueur(0)); // Initialisation de l’attribut jc, au 1er joueur de la liste
        remplirListeJoueurs(); // Remplissage de liste déroulante avec les noms des pseudos des joueurs
        SoldeJoueur.setText(jc.getPseudo() + " dispose de " + jc.getSolde() + "€");
        initCarte(); // création des boutons pour la carte
        afficheCarte(); // Affiche valeurs de la carte sur les boutons
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panneau = new javax.swing.JPanel();
        jPanelBAS = new javax.swing.JPanel();
        SoldeJoueur = new javax.swing.JLabel();
        jPanelBOUTON = new javax.swing.JPanel();
        ListeJoueurs = new javax.swing.JComboBox<>();
        AutreChoix = new javax.swing.JButton();
        Acheter = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acheter une ou plusieurs cartes");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        getContentPane().add(Panneau, java.awt.BorderLayout.CENTER);

        jPanelBAS.setLayout(new java.awt.GridLayout(2, 1));

        SoldeJoueur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanelBAS.add(SoldeJoueur);

        jPanelBOUTON.setLayout(new java.awt.GridLayout(1, 4));

        ListeJoueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeJoueursActionPerformed(evt);
            }
        });
        jPanelBOUTON.add(ListeJoueurs);

        AutreChoix.setText("Autre choix");
        AutreChoix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutreChoixActionPerformed(evt);
            }
        });
        jPanelBOUTON.add(AutreChoix);

        Acheter.setText("Acheter");
        Acheter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcheterActionPerformed(evt);
            }
        });
        jPanelBOUTON.add(Acheter);

        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });
        jPanelBOUTON.add(Quitter);

        jPanelBAS.add(jPanelBOUTON);

        getContentPane().add(jPanelBAS, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListeJoueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeJoueursActionPerformed
        // TODO add your handling code here:
        jc = ljc.getJoueur(ListeJoueurs.getSelectedIndex()); // fixe le joueur courant (jc) au joueur selectionné
        SoldeJoueur.setText(jc.getPseudo() + " dispose de " + jc.getSolde() + "€");
    }//GEN-LAST:event_ListeJoueursActionPerformed

    private void AcheterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcheterActionPerformed
        // TODO add your handling code here:
        achat = jc.acheter(cc);
        if (achat == true){ // Si la carte est achetée
            SoldeJoueur.setText(jc.getPseudo() + " dispose maintenant de " + jc.getSolde() + "€");
            initCarte(); // Nouvelle carte générée
            afficheCarte(); // Actualisation de la carte
        } else {
            SoldeJoueur.setText(jc.getPseudo() + " a un solde insuffisant ou déjà deux cartes" );
        }
    }//GEN-LAST:event_AcheterActionPerformed

    private void AutreChoixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutreChoixActionPerformed
        // TODO add your handling code here:
        cc = new CarteLoto(nbCol, nbNum);
        initCarte(); // Nouvelle carte générée
        afficheCarte();
    }//GEN-LAST:event_AutreChoixActionPerformed

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_QuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AchatCarteDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AchatCarteDlg dialog = new AchatCarteDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acheter;
    private javax.swing.JButton AutreChoix;
    private javax.swing.JComboBox<String> ListeJoueurs;
    private javax.swing.JPanel Panneau;
    private javax.swing.JButton Quitter;
    private javax.swing.JLabel SoldeJoueur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelBAS;
    private javax.swing.JPanel jPanelBOUTON;
    // End of variables declaration//GEN-END:variables

}
