/**
    Classe dérivée de jDialog pour l'ajout d'un lot
**/
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
/**
 *
 * @author thomasnicolle
 */
public class AjoutLotDlg extends javax.swing.JDialog {
    
    // Attributs
    boolean ok; // Permet de vérifier si bouton vérifier cliqué
    Lot l; // Permet de stocker les infos du nouveau lot
    PanneauImage pan; // jPanel pour afficher image selectionne
    
    // Guetters
    public boolean getOk() {
        return ok;
    }

    public Lot getLot() {
        return l;
    }

    public PanneauImage getPan() {
        return pan;
    }
    
    // Setters
    public void setOk(boolean ok) {
        this.ok = ok;
    }

    public void setLot(Lot l) {
        this.l = l;
    }

    public void setPan(PanneauImage pan) {
        this.pan = pan;
    }
    
    // Méthodes
    public void initPrix() { // Initialise les coûts possible d'un lot 
        for (int i = 0; i < 50; i += 10) { // prix compris entre 0 et 50
            ListePrix.addItem(i + "");
        }
    }

    // Constructeur
    public AjoutLotDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initPrix(); // initialisation liste prix
        ListePrix.setVisible(false);
        pan = new PanneauImage();
        jPanelCENTRE.add(pan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categorie = new javax.swing.ButtonGroup();
        niveau = new javax.swing.ButtonGroup();
        jPanelSUD = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelDROIT = new javax.swing.JPanel();
        descriptif = new javax.swing.JTextField();
        Categorie = new javax.swing.JPanel();
        boncadeau = new javax.swing.JRadioButton();
        objet = new javax.swing.JRadioButton();
        Niveau = new javax.swing.JPanel();
        nv1 = new javax.swing.JRadioButton();
        nv2 = new javax.swing.JRadioButton();
        nv3 = new javax.swing.JRadioButton();
        ListePrix = new javax.swing.JComboBox<>();
        Parcourir = new javax.swing.JButton();
        jPanelCENTRE = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelSUD.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanelSUD.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanelSUD.add(Valider);

        getContentPane().add(jPanelSUD, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saisie d'un nouveau lot");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanelDROIT.setLayout(new java.awt.GridLayout(5, 1));
        jPanelDROIT.add(descriptif);

        Categorie.setLayout(new java.awt.GridLayout(1, 2));

        categorie.add(boncadeau);
        boncadeau.setText("Bon cadeau");
        boncadeau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boncadeauActionPerformed(evt);
            }
        });
        Categorie.add(boncadeau);

        categorie.add(objet);
        objet.setText("Objet");
        objet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                objetActionPerformed(evt);
            }
        });
        Categorie.add(objet);

        jPanelDROIT.add(Categorie);

        Niveau.setLayout(new java.awt.GridLayout(1, 3));

        niveau.add(nv1);
        nv1.setText("1");
        Niveau.add(nv1);

        niveau.add(nv2);
        nv2.setText("2");
        Niveau.add(nv2);

        niveau.add(nv3);
        nv3.setText("3");
        Niveau.add(nv3);

        jPanelDROIT.add(Niveau);

        jPanelDROIT.add(ListePrix);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanelDROIT.add(Parcourir);

        getContentPane().add(jPanelDROIT, java.awt.BorderLayout.EAST);

        jPanelCENTRE.setLayout(new java.awt.GridLayout(4, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Descriptif");
        jPanelCENTRE.add(jLabel2);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Catégorie");
        jPanelCENTRE.add(jLabel3);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Niveau");
        jPanelCENTRE.add(jLabel4);

        getContentPane().add(jPanelCENTRE, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        ok = false; // false si lon annule l ajout du joueur
        this.setVisible(false); // fenetre cache
        this.dispose(); // la fenetre se ferme
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        l = new Lot(); // création de l'instance de type joueur
        l.setDescription(descriptif.getText()); // recup description du lot
        if (boncadeau.isSelected()) { // recup la categorie du lot
            l.setCategorie(1);
        } else {
            l.setCategorie(2);
            l.setPhoto(new ImageIcon(pan.getImage()));
        }
        if (nv1.isSelected()) { // recup le niveau du lot
            l.setNiveau(1);
        } else if (nv2.isSelected()) {
            l.setNiveau(2);
        } else {
            l.setNiveau(3);
        }
        ok = true; // indicateur ajouter le lot
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void boncadeauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boncadeauActionPerformed
        // TODO add your handling code here:
        Parcourir.setVisible(false);
        pan.setVisible(false);
        ListePrix.setVisible(true);
    }//GEN-LAST:event_boncadeauActionPerformed

    private void objetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_objetActionPerformed
        // TODO add your handling code here:
        ListePrix.setVisible(false);
        pan.setVisible(true);
        Parcourir.setVisible(true);
    }//GEN-LAST:event_objetActionPerformed

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser(); // boîte de dialogue prédéfinie, création d’un instance
        // on l’ouvre ici, par la méthode showDialog(…)
        if (jf.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { // si on a validé, on récupère le chemin complet du fichier sélectionné (path)
             // getSelectedFile() retourne un objet de type File, getPath() donne le chemin pour cet objet
            String path = jf.getSelectedFile().getPath(); // chemin complet;
            // on crée une instance d’une Image avec ce fichier
            Image img = Toolkit.getDefaultToolkit().getImage(path);
            // on affecte au panneau qui va se dessiner
            pan.setImage(img);
        }
    }//GEN-LAST:event_ParcourirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutLotDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutLotDlg dialog = new AjoutLotDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel Categorie;
    private javax.swing.JComboBox<String> ListePrix;
    private javax.swing.JPanel Niveau;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Valider;
    private javax.swing.JRadioButton boncadeau;
    private javax.swing.ButtonGroup categorie;
    private javax.swing.JTextField descriptif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCENTRE;
    private javax.swing.JPanel jPanelDROIT;
    private javax.swing.JPanel jPanelSUD;
    private javax.swing.ButtonGroup niveau;
    private javax.swing.JRadioButton nv1;
    private javax.swing.JRadioButton nv2;
    private javax.swing.JRadioButton nv3;
    private javax.swing.JRadioButton objet;
    // End of variables declaration//GEN-END:variables
}
