/**
    Classe dérivée de jDialog pour ajouter un joueur au jeu
**/
import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
/**
 *
 * @author thomasnicolle
 */
public class AjoutJoueurDlg extends javax.swing.JDialog {
    
    // Attributs
    boolean ok; // Permet de vérifier si bouton vérifier cliqué
    Joueur nj; // Permet de stocker les infos du nouveau joueur
    
    // Getters
    public boolean getOk(){
        return this.ok;
    }
    
    public Joueur getJoueur(){
        return this.nj;
    }
    
    // Setters
    public void setLabelSolde(String solde) {
        this.SaisieSolde.setText(solde);
    }
    
    // Constructeur
    public AjoutJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelGAUCHE = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanelDROITE = new javax.swing.JPanel();
        SaisiePseudo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButtonChoisirCouleur = new javax.swing.JButton();
        SaisieCouleur = new javax.swing.JPanel();
        SaisieSolde = new javax.swing.JLabel();
        jPanelBAS = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saisie d'un nouveau joueur");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanelGAUCHE.setLayout(new java.awt.GridLayout(4, 1));

        jLabel4.setText("Pseudo");
        jPanelGAUCHE.add(jLabel4);

        jLabel6.setText("Couleur");
        jPanelGAUCHE.add(jLabel6);

        jLabel7.setText("Solde");
        jPanelGAUCHE.add(jLabel7);

        getContentPane().add(jPanelGAUCHE, java.awt.BorderLayout.WEST);

        jPanelDROITE.setLayout(new java.awt.GridLayout(4, 1));
        jPanelDROITE.add(SaisiePseudo);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jButtonChoisirCouleur.setText("Choisir couleur");
        jButtonChoisirCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChoisirCouleurActionPerformed(evt);
            }
        });
        jPanel7.add(jButtonChoisirCouleur);
        jPanel7.add(SaisieCouleur);

        jPanelDROITE.add(jPanel7);
        jPanelDROITE.add(SaisieSolde);

        getContentPane().add(jPanelDROITE, java.awt.BorderLayout.EAST);

        jPanelBAS.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanelBAS.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanelBAS.add(Valider);

        getContentPane().add(jPanelBAS, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        ok = false; // false si lon annule l ajout du joueur
        this.setVisible(false); // fenetre cache
        this.dispose(); // la fenetre se ferme
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        nj = new Joueur(); // création de l'instance de type joueur
        nj.setPseudo(SaisiePseudo.getText()); // changement du pseudo
        nj.setCouleur(SaisieCouleur.getBackground()); // attribution de la couleur choisi
        nj.setSolde(Double.parseDouble(SaisieSolde.getText())); // attribution du solde
        ok = true; // indicateur ajouter le joueur
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ValiderActionPerformed

    private void jButtonChoisirCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChoisirCouleurActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(rootPane, "Choisir couleur", Color.white); // ouvre une boite de dialogue pour choisir couleur et attribut directement à la variable c de type couleur
        SaisieCouleur.setBackground(c); // change la couleur du pannel par la couleur choisi
    }//GEN-LAST:event_jButtonChoisirCouleurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjoutJoueurDlg dialog = new AjoutJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JPanel SaisieCouleur;
    private javax.swing.JTextField SaisiePseudo;
    private javax.swing.JLabel SaisieSolde;
    private javax.swing.JButton Valider;
    private javax.swing.JButton jButtonChoisirCouleur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBAS;
    private javax.swing.JPanel jPanelDROITE;
    private javax.swing.JPanel jPanelGAUCHE;
    // End of variables declaration//GEN-END:variables
}
