/**
    Classe dérivée de jDialog pour paramétrer le jeu
**/
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author thomasnicolle
 */
public class OptionDlg extends javax.swing.JDialog {
    
    // Attributs
    private int choixOpt; // récupère l'option choisi parmis les trois
    private int nbCol; // stock le nbr de colonne voulu par l'utilisateur
    private int nbNum; // stock le nbr de numero voulu par l'utilisateur

    // Guetters
    public int getNbCol() {
        return nbCol;
    }

    public int getChoix() {
        return choixOpt;
    }

    public int getNbNum() {
        return nbNum;
    }

    private void remplirComboCol() { // Rempli la combobox avec des nombres entre un et quatre
        for (int i = 1; i <= 5; i++) {
            ComboNbCol.addItem(Integer.toString(i));
        }
    }

    /**
     * Creates new form OptionDlg
     */
    
    // Constructeurs
    private OptionDlg(JFrame jFrame, boolean b) { // généré car ajout de plusieurs paramètres dans le constructeur
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public OptionDlg(java.awt.Frame parent, boolean modal, boolean ca, int nc, int nn) {
        super(parent, modal);
        initComponents();
        remplirComboCol(); // Méthode qui permet d’initialiser les valeurs de la liste déroulante à 5,6,7,8 et 9.
        // Cocher l’option Quine par défaut – Les boutons doivent être groupés
        Quine.setSelected(true);
        // Fixer le choix de l’option de jeu à 1 
        choixOpt = 1;
        if (!ca) { // test si des cartes ont déjà été achetées
            // Fixer le nombre de colonnes à 5 et le nombre de numéros à 5
            nbCol = 5;
            nbNum = 5;
        } else {
            // Fixer le nombre de colonnes et de numéros aux valeurs reçues en paramètres
            nbCol = nc;
            nbNum = nn;
            // Afficher la valeur du nombre de numéros dans la zone d’édition (JTextField)
            NbNumero.setText(String.valueOf(nbNum));
            // Sélectionner dans la liste déroulante l’index de la valeur du nombre de colonnes 
            // en utilisant la méthode (setSelectedIndex(..))
            ComboNbCol.setSelectedIndex(nbCol);
            // Rendre la liste et la zone d’édition non utilisables, en utilisant la méthode setEnabled(boolean)
            ComboNbCol.setEnabled(false);
            NbNumero.setEnabled(false);
            // Afficher le message : « Nb de colonnes et de numéros non modifiables » 
            // dans le JLabel nommé « Message »
            Message.setText("Nb de colonnes et de numéros non modifiables");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Option = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanelSUD = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();
        jPanelCENTRE = new javax.swing.JPanel();
        jPanelGAUCHE = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Quine = new javax.swing.JRadioButton();
        dQuine = new javax.swing.JRadioButton();
        cPlein = new javax.swing.JRadioButton();
        jPanelDROITE = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ComboNbCol = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        NbNumero = new javax.swing.JTextField();
        Message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Options du jeu");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanelSUD.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanelSUD.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanelSUD.add(Valider);

        getContentPane().add(jPanelSUD, java.awt.BorderLayout.SOUTH);

        jPanelCENTRE.setLayout(new java.awt.GridLayout(1, 2));

        jPanelGAUCHE.setLayout(new java.awt.GridLayout(4, 1));

        jLabel2.setText("Comment voulez-vous jouer ?");
        jPanelGAUCHE.add(jLabel2);

        Option.add(Quine);
        Quine.setText("Quine - Une ligne complète");
        jPanelGAUCHE.add(Quine);

        Option.add(dQuine);
        dQuine.setText("Double Quine - Deux lignes complètes");
        jPanelGAUCHE.add(dQuine);

        Option.add(cPlein);
        cPlein.setText("Carton plein - Trois lignes complètes");
        jPanelGAUCHE.add(cPlein);

        jPanelCENTRE.add(jPanelGAUCHE);

        jPanelDROITE.setLayout(new java.awt.GridLayout(4, 2));

        jLabel3.setText("Configuration des cartons");
        jPanelDROITE.add(jLabel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 165, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jPanelDROITE.add(jPanel1);

        jLabel4.setText("Combien de colonnes ?");
        jPanelDROITE.add(jLabel4);

        jPanelDROITE.add(ComboNbCol);

        jLabel5.setText("Combien de numéros ?");
        jPanelDROITE.add(jLabel5);
        jPanelDROITE.add(NbNumero);
        jPanelDROITE.add(Message);

        jPanelCENTRE.add(jPanelDROITE);

        getContentPane().add(jPanelCENTRE, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        if (Quine.isSelected()) { // 1 = quine
            choixOpt = 1;
        }
        if (dQuine.isSelected()) { // 2 = Double quine
            choixOpt = 2;
        }
        if (cPlein.isSelected()) { // 3 = Carton plein
            choixOpt = 3;
        }
        nbCol = Integer.parseInt(ComboNbCol.getSelectedItem().toString()); // recup et conversion valeur String de la combo box
        if (NbNumero.getText().equals(null)) {
            JOptionPane.showMessageDialog(rootPane, "Aucun numero entré !"); // Affichage fenêtre erreur
        } else {
            nbNum = Integer.parseInt(NbNumero.getText()); // recup de la donnée écrite et conversion en entier
            if (nbNum < 5 || nbNum > nbCol * 3) {
                JOptionPane.showMessageDialog(rootPane, "Erreur nombre de numéro");
            } else {
                this.setVisible(false);// cache la fenêtre
                this.dispose(); // ferme la fenêtre
            }
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); // cache la fenêtre
        this.dispose(); // ferme la fenêtre
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionDlg dialog = new OptionDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JComboBox<String> ComboNbCol;
    private javax.swing.JLabel Message;
    private javax.swing.JTextField NbNumero;
    private javax.swing.ButtonGroup Option;
    private javax.swing.JRadioButton Quine;
    private javax.swing.JButton Valider;
    private javax.swing.JRadioButton cPlein;
    private javax.swing.JRadioButton dQuine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCENTRE;
    private javax.swing.JPanel jPanelDROITE;
    private javax.swing.JPanel jPanelGAUCHE;
    private javax.swing.JPanel jPanelSUD;
    // End of variables declaration//GEN-END:variables
}
