/**
    Classe dérivée de jDialog pour visualiser infos du joueurs
**/
import javax.swing.JFrame;
/**
 *
 * @author thomasnicolle
 */
public class VisuJoueurDlg extends javax.swing.JDialog {
    
    // Constructeur avec en paramètre les données du jouer transmise par l'application principale
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, Joueur VisuJoueur) {
        super(parent, modal); // Constructeur class jDialog
        initComponents(); // Construction de l'interface
        InfoPseudo.setText(VisuJoueur.getPseudo()); // Affiche les informations du joueur dans les catégories respectives
        InfoCouleur.setBackground(VisuJoueur.getCouleur());
        InfoSolde.setText("" + VisuJoueur.getSolde());
        if (VisuJoueur.getMesLots().getNbLot() > 0) { // Si le joueur a gagné des lots
            for (int i = 0; i < VisuJoueur.getMesLots().getNbLot(); i++) {
                InfoLot.append(VisuJoueur.getMesLots().getLot(i).getDescription() + "\n");
            }
        } else { // Si aucun lot
            InfoLot.setText("Aucun lot gagné");
        }
        InfoPhoto.setIcon(VisuJoueur.getPhoto());
    }

    private VisuJoueurDlg(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanelCENTRE = new javax.swing.JPanel();
        jPanelGAUCHE = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        InfoPseudo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        InfoCouleur = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        InfoSolde = new javax.swing.JLabel();
        jPanelDROIT = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoLot = new javax.swing.JTextArea();
        InfoPhoto = new javax.swing.JButton();
        jPanelBAS = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Fermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Informations relatives à un joueur");
        getContentPane().add(jLabel8, java.awt.BorderLayout.NORTH);

        jPanelCENTRE.setLayout(new java.awt.GridLayout(1, 2));

        jPanelGAUCHE.setLayout(new java.awt.GridLayout(3, 2));

        jLabel9.setText("Pseudo");
        jPanelGAUCHE.add(jLabel9);
        jPanelGAUCHE.add(InfoPseudo);

        jLabel11.setText("Couleur");
        jPanelGAUCHE.add(jLabel11);
        jPanelGAUCHE.add(InfoCouleur);

        jLabel12.setText("Solde");
        jPanelGAUCHE.add(jLabel12);
        jPanelGAUCHE.add(InfoSolde);

        jPanelCENTRE.add(jPanelGAUCHE);

        jPanelDROIT.setLayout(new java.awt.GridLayout(1, 2));

        InfoLot.setEditable(false);
        InfoLot.setColumns(20);
        InfoLot.setRows(5);
        jScrollPane2.setViewportView(InfoLot);

        jPanelDROIT.add(jScrollPane2);
        jPanelDROIT.add(InfoPhoto);

        jPanelCENTRE.add(jPanelDROIT);

        getContentPane().add(jPanelCENTRE, java.awt.BorderLayout.CENTER);

        jPanelBAS.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelBAS.add(jButton1);

        Fermer.setText("Fermer");
        Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FermerActionPerformed(evt);
            }
        });
        jPanelBAS.add(Fermer);

        getContentPane().add(jPanelBAS, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_FermerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fermer;
    private javax.swing.JPanel InfoCouleur;
    private javax.swing.JTextArea InfoLot;
    private javax.swing.JButton InfoPhoto;
    private javax.swing.JLabel InfoPseudo;
    private javax.swing.JLabel InfoSolde;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelBAS;
    private javax.swing.JPanel jPanelCENTRE;
    private javax.swing.JPanel jPanelDROIT;
    private javax.swing.JPanel jPanelGAUCHE;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
